---
- hosts: ansible-server
#  become: true

  tasks:
  - name: remove image from ansible server
    command: docker rmi simple-devops-image:latest ravikirant/simple-devops-image
    ignore_errors: yes

  - name: create docker image using war file
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /opt/kubernetes

  - name: create tag to image
    command: docker tag simple-devops-image ravikirant/simple-devops-image

  - name: push image to docker hub
    command: docker push ravikirant/simple-devops-image
    ignore_errors: yes
